version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:14.10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./postresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
  ranger-admin:
    image: ranger-admin:2.7.0
    container_name: ranger-admin
    hostname: ranger
    command: ["./bootstrap.sh"]
    depends_on:
      - postgres
    volumes:
      - ./ranger-admin/install.properties:/opt/ranger-admin/install.properties
    ports:
      - "6080:6080"
    restart: always
  ranger-usersync:
    image: ranger-usersync:2.7.0
    container_name: ranger-usersync
    hostname: usersync
    depends_on:
      - ranger-admin
    volumes:
      - ./ranger-usersync/install.properties:/opt/ranger_usersync/install.properties
    command: ["./bootstrap.sh"]
    restart: always
  es:
    image: elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-elasticsearch}"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  openldap:
    container_name: openldap
    image: osixia/openldap:1.5.0
    command: "--loglevel debug"
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
      - ./ldifs:/ldifs
    environment: 
      - LDAP_ORGANISATION=rangerlocal
      - LDAP_DOMAIN=ranger.local
      - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME:-admin}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin}
      - LDAP_CONFIG_PASSWORD=config_pass
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - LDAP_SEED_INTERNAL_LDIF_PATH=/ldifs
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

volumes:
  postgres:
    driver: local
  es_data:
    driver: local

networks:
  default:
    external:
      name: ranger-env
